### PR TITLE
Addressing @phinze's comments from https://github.com/hashicorp/terraform/pull/4401

### PR DESCRIPTION
**Pull request by bigkraig**
Mostly this is removing extra opts.OptionGroupName sets, removing optional parameters from the test case, renaming option_group_description to description, fixing the website documentation, and printing an error vs returning one.

### CODE REVIEW

**Comment by bigkraig** [comment]
@stack72 what do you think? I have now verified it with adding/removing option settings.

**Comment by stack72** [comment]
Hi @bigkraig - looks good - why are there 250+ commits though? Did you rebase this?

**Comment by bigkraig** [comment]
@stack72  yeah its the rebase, I only have the last 3 commits in there

**Comment by bigkraig** [comment]
@stack72 correction, 4 commits. I just updated the website documentation

**Comment by bigkraig** [comment]
@stack72 anything I can do to help this along?

**Comment by stack72** [comment]
Hi @bigkraig 

I jsut tried to merge this PR and it changed 2522 files. I had to revert it

Please can you rebase it against origin/master and then reopen it? 

P.

**Pull request merged**
